name: Python测试

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 检查Python版本
      run: |
        python3 --version
        which python3
    
    - name: 创建虚拟环境
      run: |
        python3 -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install flake8 pytest -i https://pypi.tuna.tsinghua.edu.cn/simple
        if [ -f requirements.txt ]; then pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple; fi
    
    - name: 代码风格检查
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: 运行测试
      run: |
        python -m pytest test_calculator.py -v || python -m unittest test_calculator.py -v
    
    - name: 运行主程序
      run: |
        python calculator.py
